---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/goreleaser --version
    register: goreleaser_output
  - debug:
      msg: '{{ goreleaser_output.stdout }}'
