---
- name: Testing andrewrothstein.goreleaser
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'goreleaser --version'
      ansible.builtin.command: goreleaser --version
      changed_when: false
      register: goreleaser_output
    - name: Output from 'goreleaser --version'
      ansible.builtin.debug:
        msg: '{{ goreleaser_output.stdout }}'
