---
- name: Look for installing in {{ goreleaser_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ goreleaser_install_dir }}'
  changed_when: false
  register: goreleaser_binary
- name: Downloading and installing goreleaser
  when: not goreleaser_binary.stat.exists
  block:
    - name: Downloading {{ goreleaser_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ goreleaser_url }}'
        dest: '{{ goreleaser_tmp_archive }}'
        checksum: '{{ goreleaser_checksum }}'
        mode: '644'
    - name: Mkdir {{ goreleaser_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ goreleaser_install_dir }}'
        state: directory
        mode: '755'
    - name: Install andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive from {{ goreleaser_tmp_archive }} into {{ goreleaser_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ goreleaser_tmp_archive }}'
        dest: '{{ goreleaser_install_dir }}'
        creates: '{{ goreleaser_install_dir }}/goreleaser'
  always:
    - name: Rm {{ goreleaser_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ goreleaser_tmp_archive }}'
        state: absent
- name: Link {{ goreleaser_link }} to {{ goreleaser_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ goreleaser_install_exe }}'
    dest: '{{ goreleaser_link }}'
    state: link
