---
- name: look for install in {{ goreleaser_install_dir }}
  become: yes
  stat:
    path: '{{ goreleaser_install_dir }}'
  changed_when: False
  register: goreleaser_binary
- when: not goreleaser_binary.stat.exists
  block:
    - name: downloading {{ goreleaser_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ goreleaser_url }}'
        dest: '{{ goreleaser_tmp_archive }}'
        checksum: '{{ goreleaser_checksum }}'
        mode: 0644
    - name: mkdir {{ goreleaser_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ goreleaser_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive from {{ goreleaser_tmp_archive }} into {{ goreleaser_install_dir }}
      become: yes
      become_user: root
      unarchive:
        src: '{{ goreleaser_tmp_archive }}'
        dest: '{{ goreleaser_install_dir }}'
        creates: '{{ goreleaser_install_dir }}/goreleaser'
  always:
    - name: rm {{ goreleaser_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ goreleaser_tmp_archive }}'
        state: absent
- name: link {{ goreleaser_link }} to {{ goreleaser_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ goreleaser_install_exe }}'
    dest: '{{ goreleaser_link }}'
    state: link
